server:
  port: 8700

uri:
  api:
    clientes: http://localhost:8080
    cuentas: https://pokeapi.co

spring:
  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 10
              burstCapacity: 20
              requestedTokens: 1
        - name: CircuitBreaker
          args:
            name: clientsService
            fallbackUri: forward:/service-fallback
      routes:
        - id: all_clientes
          uri: http://localhost:8080
          predicates:
            - Method=GET
            - Path=/v1/api/cliente/all
          filters:
            - AddRequestHeader=X-GATEWAY-REQUEST-HEADER,GATEWAY-SOLICITUD
            - AddResponseHeader=X-GATEWAY-RESPONSE-HEADER,GATEWAY-RESPONSE
        - id: all_clientes_contexto
          uri: http://localhost:8080
          predicates:
            - Method=GET
            - Path=/promerica/cliente/all
          filters:
            - RewritePath=/promerica/, /v1/api/
            - AddRequestHeader=X-GATEWAY-REQUEST-HEADER,GATEWAY-SOLICITUD
            - AddResponseHeader=X-GATEWAY-RESPONSE-HEADER,GATEWAY-RESPONSE
        - id: cliente
          uri: http://localhost:8080
          predicates:
            - Method=GET,POST,PUT
            - Path=/v1/api/cliente/{id}
          filters:
            - AddRequestHeader=X-GATEWAY-REQUEST-HEADER,GATEWAY-SOLICITUD
            - AddResponseHeader=X-GATEWAY-RESPONSE-HEADER,GATEWAY-RESPONSE
        - id: cliente_contexto
          uri: http://localhost:8080
          predicates:
            - Method=GET,POST,PUT
            - Path=/promerica/cliente/{id}
          filters:
            - RewritePath=/promerica/, /v1/api/
            - AddRequestHeader=X-GATEWAY-REQUEST-HEADER,GATEWAY-SOLICITUD
            - AddResponseHeader=X-GATEWAY-RESPONSE-HEADER,GATEWAY-RESPONSE



